--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Server generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

if RunService:IsClient() then
	error("Cannot use the server module on the client!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["ZAP"] = {} }
elseif not _G.__ZAP["ZAP"] then
	_G.__ZAP["ZAP"] = {}
elseif _G.__ZAP["ZAP"]["ZAP"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of ZAP, remote_folder of ZAP and the version of {_G.__ZAP["ZAP"]["ZAP"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["ZAP"]["ZAP"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		WaitForServer = table.freeze({
			SetCallback = noop
		}),
		OnUnreliableUpdates = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		OnReliableUpdates = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		OnReceiveFull = table.freeze({
			SetCallback = noop
		}),
		MoveInput = table.freeze({
			SetCallback = noop
		}),
		KickBall = table.freeze({
			SetCallback = noop
		}),
	}) :: Events
end

local remotes = ReplicatedStorage:FindFirstChild("ZAP")
if remotes == nil then
	remotes = Instance.new("Folder")
	remotes.Name = "ZAP"
	remotes.Parent = ReplicatedStorage
end

local reliable = remotes:FindFirstChild("ZAP_RELIABLE")
if reliable == nil then
	reliable = Instance.new("RemoteEvent")
	reliable.Name = "ZAP_RELIABLE"
	reliable.Parent = remotes
end

local function getOrCreateUnreliableRemote(name: string): UnreliableRemoteEvent
	local remote = remotes:FindFirstChild(name)

	if remote == nil then
		remote = Instance.new("UnreliableRemoteEvent")
		remote.Name = name
		remote.Parent = remotes
	end

	return remote
end

local unreliable = { getOrCreateUnreliableRemote("ZAP_UNRELIABLE_0") }
assert(unreliable[1]:IsA("UnreliableRemoteEvent"), "Expected ZAP_UNRELIABLE_0 to be an UnreliableRemoteEvent")
local player_map = {}

local function load_player(player: Player)
	if player_map[player] then
		load(player_map[player])
	else
		load_empty()
	end
end

Players.PlayerRemoving:Connect(function(player)
	player_map[player] = nil
end)
export type InputFrame = ({
	["X"]: (number),
	["Z"]: (number),
	["Tick"]: (number),
	["Yaw"]: (number),
	["Pitch"]: (number),
	["Flags"]: (number),
	["RenderFrame"]: (number),
})

local function SendEvents()
	for player, outgoing in player_map do
		if outgoing.used > 0 then
			local buff = buffer.create(outgoing.used)
			buffer.copy(buff, 0, outgoing.buff, 0, outgoing.used)

			reliable:FireClient(player, buff, outgoing.inst)

			outgoing.buff = buffer.create(64)
			outgoing.used = 0
			outgoing.size = 64
			table.clear(outgoing.inst)
		end
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(3)
local unreliable_events = table.create(1)
reliable.OnServerEvent:Connect(function(player, buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- KickBall
			local value
			value = {  }
			value["ChargeTime"] = buffer.readf32(incoming_buff, read(4))
			value["Yaw"] = buffer.readf32(incoming_buff, read(4))
			if reliable_events[0] then
				task.spawn(reliable_events[0], player, value)
			end
		elseif id == 1 then -- WaitForServer
			local call_id = buffer.readu8(buff, read(1))
			local value
			if reliable_events[1] then
				local ret_1, ret_2 = reliable_events[1](player, value)
				load_player(player)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, 1)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, call_id)
				local len_1 = buffer.len(ret_1)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_1)
				alloc(len_1)
				buffer.copy(outgoing_buff, outgoing_apos, ret_1, 0, len_1)
				local len_2 = #ret_2
				assert(len_2 <= 256, "value is more than 256!")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_2)
				for i_1 = 1, len_2 do
					local val_1 = ret_2[i_1]
					local len_3 = #val_1
					assert(len_3 <= 256, "value is more than 256!")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_3)
					for i_2 = 1, len_3 do
						local val_2 = val_1[i_2]
						table.insert(outgoing_inst, val_2)
					end
				end
				player_map[player] = save()
			end
		elseif id == 2 then -- OnReceiveFull
			local call_id = buffer.readu8(buff, read(1))
			local value
			if reliable_events[2] then
				local ret_1, ret_2 = reliable_events[2](player, value)
				load_player(player)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, 2)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, call_id)
				local len_4 = buffer.len(ret_1)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_4)
				alloc(len_4)
				buffer.copy(outgoing_buff, outgoing_apos, ret_1, 0, len_4)
				local len_5 = #ret_2
				assert(len_5 <= 256, "value is more than 256!")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_5)
				for i_3 = 1, len_5 do
					local val_3 = ret_2[i_3]
					local len_6 = #val_3
					assert(len_6 <= 256, "value is more than 256!")
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, len_6)
					for i_4 = 1, len_6 do
						local val_4 = val_3[i_4]
						table.insert(outgoing_inst, val_4)
					end
				end
				player_map[player] = save()
			end
		else
			error("Unknown event id")
		end
	end
end)
unreliable[1].OnServerEvent:Connect(function(player, buff, inst) -- MoveInput
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local value
	value = {  }
	local len_7 = buffer.readu8(incoming_buff, read(1))
	assert(len_7 <= 32, "value is more than 32!")
	value["History"] = table.create(len_7)
	for i_5 = 1, len_7 do
		local val_5
		val_5 = {  }
		val_5["X"] = buffer.readf32(incoming_buff, read(4))
		val_5["Z"] = buffer.readf32(incoming_buff, read(4))
		val_5["Tick"] = buffer.readu32(incoming_buff, read(4))
		val_5["Yaw"] = buffer.readf32(incoming_buff, read(4))
		val_5["Pitch"] = buffer.readf32(incoming_buff, read(4))
		val_5["Flags"] = buffer.readu32(incoming_buff, read(4))
		val_5["RenderFrame"] = buffer.readf32(incoming_buff, read(4))
		value["History"][i_5] = val_5
	end
	if unreliable_events[0] then
		task.spawn(unreliable_events[0], player, value)
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	WaitForServer = {
		SetCallback = function(Callback: (Player: Player) -> ((buffer), ({ ({ (Instance) }) }))): () -> ()
			reliable_events[1] = Callback
			return function()
				reliable_events[1] = nil
			end
		end,
	},
	OnUnreliableUpdates = {
		Fire = function(Player: Player, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			local len_8 = buffer.len(buf)
			assert(len_8 <= 512, "value is more than 512!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_8)
			alloc(len_8)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_8)
			local len_9 = #variants
			assert(len_9 <= 32, "value is more than 32!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_9)
			for i_6 = 1, len_9 do
				local val_6 = variants[i_6]
				local len_10 = #val_6
				assert(len_10 <= 32, "value is more than 32!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_10)
				for i_7 = 1, len_10 do
					local val_7 = val_6[i_7]
					table.insert(outgoing_inst, val_7)
				end
			end
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			unreliable[1]:FireClient(Player, buff, outgoing_inst)
		end,
		FireAll = function(buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			local len_11 = buffer.len(buf)
			assert(len_11 <= 512, "value is more than 512!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_11)
			alloc(len_11)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_11)
			local len_12 = #variants
			assert(len_12 <= 32, "value is more than 32!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_12)
			for i_8 = 1, len_12 do
				local val_8 = variants[i_8]
				local len_13 = #val_8
				assert(len_13 <= 32, "value is more than 32!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_13)
				for i_9 = 1, len_13 do
					local val_9 = val_8[i_9]
					table.insert(outgoing_inst, val_9)
				end
			end
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			unreliable[1]:FireAllClients(buff, outgoing_inst)
		end,
		FireExcept = function(Except: Player, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			local len_14 = buffer.len(buf)
			assert(len_14 <= 512, "value is more than 512!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_14)
			alloc(len_14)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_14)
			local len_15 = #variants
			assert(len_15 <= 32, "value is more than 32!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_15)
			for i_10 = 1, len_15 do
				local val_10 = variants[i_10]
				local len_16 = #val_10
				assert(len_16 <= 32, "value is more than 32!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_16)
				for i_11 = 1, len_16 do
					local val_11 = val_10[i_11]
					table.insert(outgoing_inst, val_11)
				end
			end
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					unreliable[1]:FireClient(player, buff, outgoing_inst)
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			local len_17 = buffer.len(buf)
			assert(len_17 <= 512, "value is more than 512!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_17)
			alloc(len_17)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_17)
			local len_18 = #variants
			assert(len_18 <= 32, "value is more than 32!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_18)
			for i_12 = 1, len_18 do
				local val_12 = variants[i_12]
				local len_19 = #val_12
				assert(len_19 <= 32, "value is more than 32!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_19)
				for i_13 = 1, len_19 do
					local val_13 = val_12[i_13]
					table.insert(outgoing_inst, val_13)
				end
			end
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			for _, player in List do
				unreliable[1]:FireClient(player, buff, outgoing_inst)
			end
		end,
		FireSet = function(Set: { [Player]: any }, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			local len_20 = buffer.len(buf)
			assert(len_20 <= 512, "value is more than 512!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_20)
			alloc(len_20)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_20)
			local len_21 = #variants
			assert(len_21 <= 32, "value is more than 32!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_21)
			for i_14 = 1, len_21 do
				local val_14 = variants[i_14]
				local len_22 = #val_14
				assert(len_22 <= 32, "value is more than 32!")
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, len_22)
				for i_15 = 1, len_22 do
					local val_15 = val_14[i_15]
					table.insert(outgoing_inst, val_15)
				end
			end
			local buff = buffer.create(outgoing_used)
			buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)
			for player in Set do
				unreliable[1]:FireClient(player, buff, outgoing_inst)
			end
		end,
	},
	OnReliableUpdates = {
		Fire = function(Player: Player, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_23 = buffer.len(buf)
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_23)
			alloc(len_23)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_23)
			local len_24 = #variants
			assert(len_24 <= 256, "value is more than 256!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_24)
			for i_16 = 1, len_24 do
				local val_16 = variants[i_16]
				local len_25 = #val_16
				assert(len_25 <= 256, "value is more than 256!")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_25)
				for i_17 = 1, len_25 do
					local val_17 = val_16[i_17]
					table.insert(outgoing_inst, val_17)
				end
			end
			player_map[Player] = save()
		end,
		FireAll = function(buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_26 = buffer.len(buf)
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_26)
			alloc(len_26)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_26)
			local len_27 = #variants
			assert(len_27 <= 256, "value is more than 256!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_27)
			for i_18 = 1, len_27 do
				local val_18 = variants[i_18]
				local len_28 = #val_18
				assert(len_28 <= 256, "value is more than 256!")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_28)
				for i_19 = 1, len_28 do
					local val_19 = val_18[i_19]
					table.insert(outgoing_inst, val_19)
				end
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_29 = buffer.len(buf)
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_29)
			alloc(len_29)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_29)
			local len_30 = #variants
			assert(len_30 <= 256, "value is more than 256!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_30)
			for i_20 = 1, len_30 do
				local val_20 = variants[i_20]
				local len_31 = #val_20
				assert(len_31 <= 256, "value is more than 256!")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_31)
				for i_21 = 1, len_31 do
					local val_21 = val_20[i_21]
					table.insert(outgoing_inst, val_21)
				end
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_32 = buffer.len(buf)
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_32)
			alloc(len_32)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_32)
			local len_33 = #variants
			assert(len_33 <= 256, "value is more than 256!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_33)
			for i_22 = 1, len_33 do
				local val_22 = variants[i_22]
				local len_34 = #val_22
				assert(len_34 <= 256, "value is more than 256!")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_34)
				for i_23 = 1, len_34 do
					local val_23 = val_22[i_23]
					table.insert(outgoing_inst, val_23)
				end
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, buf: (buffer), variants: ({ ({ (Instance) }) }))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_35 = buffer.len(buf)
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_35)
			alloc(len_35)
			buffer.copy(outgoing_buff, outgoing_apos, buf, 0, len_35)
			local len_36 = #variants
			assert(len_36 <= 256, "value is more than 256!")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_36)
			for i_24 = 1, len_36 do
				local val_24 = variants[i_24]
				local len_37 = #val_24
				assert(len_37 <= 256, "value is more than 256!")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_37)
				for i_25 = 1, len_37 do
					local val_25 = val_24[i_25]
					table.insert(outgoing_inst, val_25)
				end
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	OnReceiveFull = {
		SetCallback = function(Callback: (Player: Player) -> ((buffer), ({ ({ (Instance) }) }))): () -> ()
			reliable_events[2] = Callback
			return function()
				reliable_events[2] = nil
			end
		end,
	},
	MoveInput = {
		SetCallback = function(Callback: (Player: Player, Value: ({
			["History"]: ({ ({
				["X"]: (number),
				["Z"]: (number),
				["Tick"]: (number),
				["Yaw"]: (number),
				["Pitch"]: (number),
				["Flags"]: (number),
				["RenderFrame"]: (number),
			}) }),
		})) -> ()): () -> ()
			unreliable_events[0] = Callback
			return function()
				unreliable_events[0] = nil
			end
		end,
	},
	KickBall = {
		SetCallback = function(Callback: (Player: Player, Value: ({
			["ChargeTime"]: (number),
			["Yaw"]: (number),
		})) -> ()): () -> ()
			reliable_events[0] = Callback
			return function()
				reliable_events[0] = nil
			end
		end,
	},
}
type Events = typeof(returns)
return returns
